In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("stats.csv")
df

,Name,State,Notes,User,Tags,Created,Runtime,Sweep,batch_size,data_root,...,test_hemg_acc,test_hemg_auc,test_hemg_f1,test_hemg_precision,test_hemg_recall,test_rajarshi_acc,test_rajarshi_auc,test_rajarshi_f1,test_rajarshi_precision,test_rajarshi_recall
0,resnet18-real_artifact_net-aggregate-final,finished,-,NaN,NaN,2026-03-19T01:46:41.000Z,6184,NaN,128,data,...,0.965231,0.994681,0.965466,0.965732,0.965231,0.647973,0.682430,0.648289,0.648608,0.647973
1,resnet18-rgb-aggregate-final,finished,-,NaN,NaN,2026-03-19T00:44:23.000Z,3622,NaN,128,data,...,0.953476,0.994077,0.954805,0.957213,0.953476,0.655560,0.682073,0.646572,0.639750,0.655560
2,resnet18-fft-aggregate-final,finished,-,NaN,NaN,2026-03-19T00:21:54.000Z,985,NaN,128,data,...,0.673680,0.781737,0.657060,0.693053,0.673680,0.502693,0.506337,0.453320,0.501509,0.502693
3,resnet50-real_artifact_net-final,finished,-,NaN,NaN,2026-03-17T22:28:53.000Z,2643,NaN,128,data,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,resnet50-rgb-final,finished,-,NaN,NaN,2026-03-17T22:01:42.000Z,1568,NaN,128,data,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,resnet50-fft-final,finished,-,NaN,NaN,2026-03-17T21:48:01.000Z,488,NaN,128,data,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,resnet18-real_artifact_net-final-v2,finished,-,NaN,NaN,2026-03-16T22:56:52.000Z,535,NaN,128,data,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,resnet18-rgb-final,finished,-,NaN,NaN,2026-03-16T22:25:57.000Z,704,NaN,128,data,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,resnet18-fft-final,finished,-,NaN,NaN,2026-03-16T22:16:15.000Z,414,NaN,128,data,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.columns, len(df.columns)

(Index(['Name', 'State', 'Notes', 'User', 'Tags', 'Created', 'Runtime', 'Sweep',
        'batch_size', 'data_root',
        ...
        'test_hemg_acc', 'test_hemg_auc', 'test_hemg_f1', 'test_hemg_precision',
        'test_hemg_recall', 'test_rajarshi_acc', 'test_rajarshi_auc',
        'test_rajarshi_f1', 'test_rajarshi_precision', 'test_rajarshi_recall'],
       dtype='str', length=157),
 157)

In [13]:
test_cols = [col for col in df.columns if "test/" in col]
relevant_cols = ["Name"] + test_cols
relevant_cols

['Name',
 'test/acc',
 'test/auc',
 'test/f1',
 'test/loss',
 'test/precision',
 'test/recall',
 'test/cifake/acc',
 'test/cifake/auc',
 'test/cifake/f1',
 'test/cifake/loss',
 'test/cifake/precision',
 'test/cifake/recall',
 'test/hemg/acc',
 'test/hemg/auc',
 'test/hemg/f1',
 'test/hemg/loss',
 'test/hemg/precision',
 'test/hemg/recall',
 'test/rajarshi/acc',
 'test/rajarshi/auc',
 'test/rajarshi/f1',
 'test/rajarshi/loss',
 'test/rajarshi/precision',
 'test/rajarshi/recall']

In [36]:
def model_name(name:str) -> str:
    """get a nicer name of the model"""
    rename = {
        "resnet18-real_artifact_net-aggregate-final":"ResNet18 Hybrid",
        "resnet18-rgb-aggregate-final":"ResNet18 RGB",
        "resnet18-fft-aggregate-final":"ResNet18 FFT"
    }
    return rename[name]

def get_results(df, test:bool=True) -> df:
    datasets = ['cifake', 'hemg', 'rajarshi']
    metrics = ['acc', 'auc', 'f1', 'loss', 'precision', 'recall']
    metric_titles = {
        "acc": "Accuracy",
        "auc": "AUC",
        "f1": "F1",
        "loss":"Loss",
        "precision":"Precision",
        "recall":"Recall"
    }
    # Compute average across datasets for each metric
    results_df = pd.DataFrame(columns=['Name'] + metrics)
    results_df["Name"] = df["Name"]
    split = "test" if test else "train"
    for m in metrics:
        cols = [f'test/{d}/{m}' for d in datasets]
        results_df[f'{m}'] = df[cols].mean(axis=1)
    results_df = results_df.rename(columns=metric_titles)
    results_df = results_df.dropna(axis=0, how='any')
    results_df["Name"] = results_df["Name"].apply(model_name)
    return results_df

In [37]:
test_results_df = get_results(df, test=True)
train_results_df = get_results(df, test=False)

In [38]:
test_results_df

,Name,Accuracy,AUC,F1,Loss,Precision,Recall
0,ResNet18 Hybrid,0.867685,0.892127,0.867868,0.620941,0.868099,0.867685
1,ResNet18 RGB,0.862179,0.891760,0.859623,0.837716,0.858422,0.862179
2,ResNet18 FFT,0.637941,0.713217,0.613908,0.602603,0.651918,0.637941

In [39]:
train_results_df

,Name,Accuracy,AUC,F1,Loss,Precision,Recall
0,ResNet18 Hybrid,0.867685,0.892127,0.867868,0.620941,0.868099,0.867685
1,ResNet18 RGB,0.862179,0.891760,0.859623,0.837716,0.858422,0.862179
2,ResNet18 FFT,0.637941,0.713217,0.613908,0.602603,0.651918,0.637941

In [40]:
train_results_df.to_csv("train_results.csv", index=False)
test_results_df.to_csv("test_results.csv", index=False)